#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

copy_from_repo_to_app() {
  local APP="$1"
  local TMP_WORK_DIR="$2"
  verify_app_name "$APP"

  trap 'rm -rf "$TMP_WORK_DIR" > /dev/null' RETURN

  if [[ -d "$TMP_WORK_DIR/.dokku" ]] && [[ "$(ls -A "$TMP_WORK_DIR/.dokku")" ]]; then
    dokku_log_info1 "Copy files from repo to application directory..."
    for file in .dokku/*; do
      dokku_log_verbose "- Copying $(basename "$file")"
      cp -R "$file" "$DOKKU_ROOT/$APP/"
    done
  else
    dokku_log_info1 "Nothing to copy from repository to application directory"
  fi
}

copy_from_repo_to_app "$1" "$2"







